class SQLMarcacao:
    _TABLE_NAME_PACIENTE = 'paciente'
    _TABLE_NAME_SUS = 'sus_historico'
    _TABLE_NAME_DEMANDA = 'demanda'
    _TABLE_NAME = 'marcacao'
    _COL_ID = 'id'
    _COL_CPF = 'cpf'
    _COL_SUS = 'sus'
    _COL_DEMANDA_ID = 'demanda'
    _COL_DATA_SOLICITACAO = 'data_solicitacao'
    _COL_DATA_MARCACAO = 'data_marcacao'
    _COL_NAME_PACIENTE = 'nome'
    _CAMPOS_OBRIGATORIOS = [_COL_DEMANDA_ID,_COL_SUS,_COL_CPF]

    _CREATE_TABLE = f'CREATE TABLE IF NOT EXISTS {_TABLE_NAME}' \
                    f'(id serial primary key,' \
                    f'{_COL_SUS} varchar(15),' \
                    f'{_COL_CPF} varchar(14),' \
                    f'{_COL_DEMANDA_ID} integer references {_TABLE_NAME_DEMANDA}({_COL_ID}),' \
                    f'{_COL_DATA_SOLICITACAO} varchar(10),' \
                    f'{_COL_DATA_MARCACAO} varchar(10))'

    _INSERTO_INTO = f'INSERT INTO {_TABLE_NAME} ({_COL_SUS}, {_COL_CPF}, {_COL_DEMANDA_ID}, {_COL_DATA_SOLICITACAO}, {_COL_DATA_MARCACAO}) values (%s, %s, %s, %s, %s);'
    _UPDATE_MARCACAO = f'UPDATE {_TABLE_NAME} SET {_COL_DATA_MARCACAO} = %s WHERE {_COL_ID} = %s;'
    _SELECT_ALL = f'SELECT m.{_COL_ID}, m.{_COL_SUS}, m.{_COL_CPF}, d.{_TABLE_NAME_DEMANDA} , m.{_COL_DATA_SOLICITACAO}, m.{_COL_DATA_MARCACAO} FROM {_TABLE_NAME} m INNER JOIN {_TABLE_NAME_DEMANDA} d ON m.{_COL_DEMANDA_ID} = d.{_COL_ID};'
    _SELECT_BY_SUS_OR_CPF = f'SELECT d.{_COL_DEMANDA_ID}, m.{_COL_DATA_SOLICITACAO} FROM {_TABLE_NAME} m INNER JOIN {_TABLE_NAME_DEMANDA} d ON m.{_COL_DEMANDA_ID} = d.{_COL_ID} WHERE (m.{_COL_SUS} = %s OR m.{_COL_CPF} = %s) AND m.{_COL_DEMANDA_ID} = %s AND m.{_COL_DATA_MARCACAO} IS NULL;'
    _LIST_DEMANDA_REPRIMIDA_MAIS_ANTIGA = f'SELECT d.{_COL_DEMANDA_ID}, MIN(m.{_COL_DATA_SOLICITACAO}) AS {_COL_DATA_SOLICITACAO} FROM {_TABLE_NAME} m INNER JOIN {_TABLE_NAME_DEMANDA} d ON m.{_COL_DEMANDA_ID} = d.{_COL_ID} WHERE {_COL_DATA_MARCACAO} IS NULL GROUP BY d.{_COL_DEMANDA_ID} ORDER BY {_COL_DATA_SOLICITACAO};'
    _LIST_DEMANDA_REPRIMIDA = f'SELECT d.{_COL_DEMANDA_ID}, m.{_COL_DATA_SOLICITACAO} AS {_COL_DATA_SOLICITACAO} FROM {_TABLE_NAME} m INNER JOIN {_TABLE_NAME_DEMANDA} d ON m.{_COL_DEMANDA_ID} = d.{_COL_ID} WHERE {_COL_DATA_MARCACAO} IS NULL ORDER BY {_COL_DATA_SOLICITACAO};'
    _SELECT_ID_MARCACAO_BY_SUS_OR_CPF_DEMANDA = f'SELECT m.{_COL_ID} ,d.{_COL_DEMANDA_ID}, m.{_COL_DATA_SOLICITACAO}, m.{_COL_DATA_MARCACAO} FROM {_TABLE_NAME} m INNER JOIN {_TABLE_NAME_DEMANDA} d ON m.{_COL_DEMANDA_ID} = d.{_COL_ID} WHERE (m.{_COL_SUS} = %s OR m.{_COL_CPF} = %s) AND m.{_COL_DEMANDA_ID} = %s AND m. {_COL_DATA_MARCACAO} IS NULL ORDER BY {_COL_DATA_SOLICITACAO} LIMIT 1;'
    _LISTA_SOLICITACOES_POR_PACIENTE = F'SELECT p.{_COL_NAME_PACIENTE}, d.{_COL_DEMANDA_ID}, m.{_COL_DATA_SOLICITACAO}, m.{_COL_DATA_MARCACAO} FROM {_TABLE_NAME} m INNER JOIN {_TABLE_NAME_PACIENTE} p ON m.{_COL_CPF} = p.{_COL_CPF} INNER JOIN {_TABLE_NAME_DEMANDA} d ON m.{_COL_DEMANDA_ID} = d.{_COL_ID} GROUP BY p.{_COL_NAME_PACIENTE}, d.{_COL_DEMANDA_ID}, m.{_COL_DATA_SOLICITACAO}, m.{_COL_DATA_MARCACAO} ORDER BY {_COL_NAME_PACIENTE}, {_COL_DEMANDA_ID};'
    _LISTA_SOLICITACOES_POR_SUS = F'SELECT p.{_COL_NAME_PACIENTE}, d.{_COL_DEMANDA_ID}, m.{_COL_DATA_SOLICITACAO}, m.{_COL_DATA_MARCACAO} FROM {_TABLE_NAME} m INNER JOIN {_TABLE_NAME_PACIENTE} p ON m.{_COL_CPF} = p.{_COL_CPF} INNER JOIN {_TABLE_NAME_DEMANDA} d ON m.{_COL_DEMANDA_ID} = d.{_COL_ID} WHERE m.{_COL_SUS} = %s'
    _LISTA_SOLICITACOES_POR_CPF = F'SELECT p.{_COL_NAME_PACIENTE}, d.{_COL_DEMANDA_ID}, m.{_COL_DATA_SOLICITACAO}, m.{_COL_DATA_MARCACAO} FROM {_TABLE_NAME} m INNER JOIN {_TABLE_NAME_PACIENTE} p ON m.{_COL_CPF} = p.{_COL_CPF} INNER JOIN {_TABLE_NAME_DEMANDA} d ON m.{_COL_DEMANDA_ID} = d.{_COL_ID} WHERE m.{_COL_CPF} = %s'
    _LISTA_SOLICITACOES_POR_DEMENDA = F'SELECT p.{_COL_NAME_PACIENTE}, d.{_COL_DEMANDA_ID}, m.{_COL_DATA_SOLICITACAO}, m.{_COL_DATA_MARCACAO} FROM {_TABLE_NAME} m INNER JOIN {_TABLE_NAME_PACIENTE} p ON m.{_COL_CPF} = p.{_COL_CPF} INNER JOIN {_TABLE_NAME_DEMANDA} d ON m.{_COL_DEMANDA_ID} = d.{_COL_ID} WHERE m.{_COL_DEMANDA_ID} = %s'